version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - |-
        JPYK_ALLOW_NO_CONFIG=1
        doit bootstrap
      - |-
        ls jupyak_config.*
          && JPYK_LOG_JSON=work/build/logs/git.json
            doit shave:git:*
      - |-
        ls jupyak_config.*
          && JPYK_LOG_JSON=work/build/logs/shave.json
            doit shave
      - |-
        JPYK_ALLOW_NO_CONFIG=1
        doit self:graph
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
conda:
  environment: .binder/environment.yml
