[lite]
gist = "7232671f04a5de8f1ce4b810f5ea8a3a"

[repos]
lumino.github.merge_with = [
    "pull/655",
    "pull/627",
]

jupyterlab.github.merge_strategy = "ort"
jupyterlab.github.merge_options = ["theirs"]
jupyterlab.github.merge_with = [
    "pull/14575",
    "pull/14597",
    "pull/14766",
    "pull/14854",
    "pull/15222",
    "pull/15347"
]
