"$schema" = "http://json-schema.org/draft-07/schema#"
title = "Yak"
description = "A description of a jupyak pull request"

[properties.env]
"$ref" = "#/$defs/CondaEnv"

[properties.env.default]
channels = [
  "conda-forge",
  "nodefaults",
]
dependencies = [
  "python ==3.11.*",
  "nodejs ==20.*",
  "yarn ==3.6.*",
  "pip",
  "hatch",
  "hatch-jupyter-builder",
  "jupyter-packaging",
  "python-build",
  "python-libarchive-c",
]

[properties.env.default.pypi_to_conda]
build = "python-build"
fastjsonschema = "python-fastjsonschema"
jupyterlab-pygments = "jupyterlab_pygments"
prometheus-client = "prometheus_client"
stack-data = "stack_data"

[properties.env.default.variables]

[properties.lite]
"$ref" = "#/$defs/LiteOptions"

[properties.repos]
type = "object"

[[properties.repos.additionalProperties.anyOf]]
"$ref" = "#/$defs/Repo"
type = "object"
title = "custom repo"

[[properties.repos.additionalProperties.anyOf]]
title = "comm"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "comm" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "comm"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/ipython/comm"

[[properties.repos.additionalProperties.anyOf]]
title = "ipykernel"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "ipykernel" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "ipykernel"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/ipython/ipykernel"

[[properties.repos.additionalProperties.anyOf]]
title = "ipython"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "ipython" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "ipython"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/ipython/ipython"

[[properties.repos.additionalProperties.anyOf]]
title = "ipywidgets"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "ipywidgets" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "ipywidgets"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter-widgets/ipywidgets"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyter_client"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "jupyter_client" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "jupyter_client"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/jupyter_client"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyter_core"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "jupyter_core" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "jupyter_core"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/jupyter_core"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyter_events"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "jupyter_events" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "jupyter_events"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/jupyter_events"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyter_server"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "jupyter_server" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "jupyter_server"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter-server/jupyter_server"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyter_server_terminals"

[[properties.repos.additionalProperties.anyOf.allOf]]
type = "object"

[properties.repos.additionalProperties.anyOf.allOf.properties.name]
type = "string"
const = "jupyter_server_terminals"

[[properties.repos.additionalProperties.anyOf.allOf]]
"$ref" = "#/$defs/Repo"

[properties.repos.additionalProperties.anyOf.default]
name = "jupyter_server_terminals"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter-server/jupyter_server_terminals"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyterlab"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "jupyterlab" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "jupyterlab"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyterlab/jupyterlab"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyterlab_server"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "jupyterlab_server" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "jupyterlab_server"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyterlab/jupyterlab_server"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyterlite"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "jupyterlite" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "jupyterlite"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyterlite/jupyterlite"

[[properties.repos.additionalProperties.anyOf]]
title = "jupyterlite_pyodide_kernel"

[[properties.repos.additionalProperties.anyOf.allOf]]
type = "object"

[properties.repos.additionalProperties.anyOf.allOf.properties.name]
type = "string"
const = "jupyterlite_pyodide_kernel"

[[properties.repos.additionalProperties.anyOf.allOf]]
"$ref" = "#/$defs/Repo"

[properties.repos.additionalProperties.anyOf.default]
name = "jupyterlite_pyodide_kernel"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyterlite/pyodide-kernel"

[[properties.repos.additionalProperties.anyOf]]
title = "lumino"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "lumino" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "lumino"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyterlab/lumino"

[[properties.repos.additionalProperties.anyOf]]
title = "nbclient"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "nbclient" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "nbclient"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/nbclient"

[[properties.repos.additionalProperties.anyOf]]
title = "nbconvert"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "nbconvert" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "nbconvert"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/nbconvert"

[[properties.repos.additionalProperties.anyOf]]
title = "nbformat"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "nbformat" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "nbformat"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/nbformat"

[[properties.repos.additionalProperties.anyOf]]
title = "notebook"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "notebook" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "notebook"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/notebook"

[[properties.repos.additionalProperties.anyOf]]
title = "notebook_shim"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "notebook_shim" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "notebook_shim"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/jupyter/notebook_shim"

[[properties.repos.additionalProperties.anyOf]]
title = "traitlets"
allOf = [
  { type = "object", properties = { name = { type = "string", const = "traitlets" } } },
  { "$ref" = "#/$defs/Repo" },
]

[properties.repos.additionalProperties.anyOf.default]
name = "traitlets"

[properties.repos.additionalProperties.anyOf.default.github]
baseline = "tree/main"
merge_options = []
merge_strategy = ""
merge_with = []
url = "https://github.com/ipython/traitlets"

["$defs".CondaEnv]
title = "CondaEnv"
description = "A description of the conda environment for doing work."

["$defs".CondaEnv.properties.channels]
type = "array"
description = "the priority-ordered set of conda URLs of channels to get packages"

["$defs".CondaEnv.properties.channels.items]
type = "string"

["$defs".CondaEnv.properties.dependencies]
type = "array"
description = "the names of conda packages (or a `pip:` object) to install"

["$defs".CondaEnv.properties.dependencies.items]
anyOf = [
  { type = "string" },
  { "$ref" = "#/$defs/PipDeps" },
]

["$defs".CondaEnv.properties.pypi_to_conda]
type = "object"
description = "names of PyPI distributions to replace with their conda-forge counterparts"

["$defs".CondaEnv.properties.variables]
type = "object"
description = "environment variables to set when the work environment is activated"

["$defs".CondaEnv.properties.variables.additionalProperties]
type = "string"

["$defs".GitHub]
title = "GitHub"
description = "Information for how to clone the baseline and PRs for this repo"

["$defs".GitHub.properties.baseline]
type = "string"
description = "the URL of the baseline HEAD"
pattern = "^(tree/[^s]+|pull/\\d+|releases/tag/[^s]+)$"

["$defs".GitHub.properties.merge_options]
type = "array"
description = "extra options for (and requiring) the ``merge_strategy``"

["$defs".GitHub.properties.merge_options.items]
type = "string"

["$defs".GitHub.properties.merge_strategy]
type = "string"
description = "a custom `--strategy` to use during `git merge`"

["$defs".GitHub.properties.merge_with]
type = "array"
description = "an optional, ordered list of branches to merge into the `baseline`"

["$defs".GitHub.properties.merge_with.items]
type = "string"
pattern = "^(tree/[^s]+|pull/\\d+|releases/tag/[^s]+)$"

["$defs".GitHub.properties.url]
type = "string"
description = "the URL of the repo"
pattern = "https://github\\.com/.*"

["$defs".JSOptions]
title = "JSOptions"
description = "JavaScript-related provisioning, building, and linking."

["$defs".JSOptions.properties.dependencies]
type = "array"
description = "the names of other members of `repos` that need to built and linked into this repo in the JS environment"

["$defs".JSOptions.properties.dependencies.items]
type = "string"

["$defs".JSOptions.properties.dist_exclude_patterns]
type = "array"
description = "regular expressions for the paths in this repo that should _not_ be built and linked in other repos"

["$defs".JSOptions.properties.dist_exclude_patterns.items]
type = "string"

["$defs".JSOptions.properties.install_exclude_resolutions]
type = "array"
description = "regular expressions for the npm `@org/pkg` names that should _not_ be installed, ever, in this repo"

["$defs".JSOptions.properties.install_exclude_resolutions.items]
type = "string"

["$defs".JSOptions.properties.link_exclude_patterns]
type = "array"
description = "regular expressions for the npm `@org/pkg` names that should _not_ be linked into this repo"

["$defs".JSOptions.properties.link_exclude_patterns.items]
type = "string"

["$defs".JSOptions.properties.tasks]
type = "object"
description = "task templates required to fulfill various js needs"

["$defs".LiteOptions]
title = "LiteOptions"
description = "options for the final jupyterlite build"

["$defs".LiteOptions.properties.gist]
type = "string"
description = "a gist ID on GitHub to use as JupyterLite contents and config"

["$defs".PipDeps]
title = "PipDeps"
description = "Eject to the `pip` ecosystem."

["$defs".PipDeps.properties.pip]
type = "array"
description = "a PEP 508 description of a pip dependency"

["$defs".PipDeps.properties.pip.items]
type = "string"

["$defs".PythonOptions]
title = "PythonOptions"
description = "Python-related provisioning, building, and linking."

["$defs".PythonOptions.properties.dependencies]
type = "array"
description = "the names of other members of `repos` that need to built and linked into this repo in the Python environment"

["$defs".PythonOptions.properties.dependencies.items]
type = "string"

["$defs".PythonOptions.properties.file_dep]
type = "array"
description = "files needed (usually created by js tasks) before and editable python install"

["$defs".PythonOptions.properties.file_dep.items]
type = "string"

["$defs".PythonOptions.properties.lab_extensions]
type = "object"
description = "paths with extra file depenendencies needed to build an extension in this repo"

["$defs".PythonOptions.properties.modules]
type = "array"
description = "the importable python names provided by this repo"

["$defs".PythonOptions.properties.modules.items]
type = "string"

["$defs".PythonOptions.properties.pyproject_tomls]
type = "array"
description = "pyproject toml files for installable packages"

["$defs".PythonOptions.properties.pyproject_tomls.items]
type = "string"

["$defs".Repo]
title = "Repo"
description = "A description of a repo."

["$defs".Repo.properties.github]
"$ref" = "#/$defs/GitHub"

["$defs".Repo.properties.js]
"$ref" = "#/$defs/JSOptions"

["$defs".Repo.properties.lite]
"$ref" = "#/$defs/RepoLiteOptions"

["$defs".Repo.properties.name]
type = "string"
description = "the duplicated name from the parent ``repos`` dictionary used for dependencies"

["$defs".Repo.properties.py]
"$ref" = "#/$defs/PythonOptions"

["$defs".Repo.properties.variables]
type = "object"
description = "environment variables to set when the work environment is activated"

["$defs".Repo.properties.variables.additionalProperties]
type = "string"

["$defs".RepoLiteOptions]
title = "RepoLiteOptions"

["$defs".RepoLiteOptions.properties.needs_pth]
type = "array"
description = "names of packages this repo provides that need to be installed before a lite site build"

["$defs".RepoLiteOptions.properties.needs_pth.items]
type = "string"

["$defs".RepoLiteOptions.properties.skip_wheel_patterns]
type = "array"
description = "paths to skip building wheels"

["$defs".RepoLiteOptions.properties.skip_wheel_patterns.items]
type = "string"

["$defs".RepoLiteOptions.properties.wheel]
type = "boolean"
description = "whether to build and ship a noarch wheel for pyodide"

["$defs".RepoLiteOptions.properties.wheel_file_dep]
type = "object"
description = "extra files needed to build a given wheel"
